title: Blogs Posts Tutorials
subtitle: a taste of computer science
author: Fanbo Xiang
email: xiangfanbo@gmail.com
description: >-
  This site is my personal blogging site. I will post practical guides
  for algorithms and set-ups.
baseurl: "/blog" 
url: "http://www.fbxiang.com" 
# twitter_username: jekyllrb
github_username:  fbxiang

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
